# Generated by Django 2.2 on 2019-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contacts',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
