# Generated by Django 2.2 on 2019-04-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0002_auto_20190409_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('pub_year', models.IntegerField(blank=True, null=True, verbose_name='Год публикации')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('binding', models.CharField(max_length=30, verbose_name='Переплет')),
                ('form', models.CharField(max_length=30, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=30, verbose_name='ISBN')),
                ('weigth', models.IntegerField(blank=True, null=True, verbose_name='Вес(гр)')),
                ('availability', models.IntegerField(blank=True, null=True, verbose_name='Активный')),
                ('activ', models.BooleanField(default=True)),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('add_date', models.DateField(blank=True, null=True, verbose_name='Дата внесения в каталог')),
                ('description', models.TextField()),
                ('author', models.ManyToManyField(blank=True, null=True, to='directory.Author', verbose_name='Автор')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Genre')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Publisher')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Serie')),
            ],
        ),
    ]
