# Generated by Django 2.2 on 2019-04-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='change_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='add_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата внесения в каталог'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='directory.Author', verbose_name='Автор'),
        ),
    ]
