# Generated by Django 2.2 on 2019-04-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190409_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='activ',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество книг в наличие'),
        ),
    ]
